# Generated by Django 4.1.9 on 2024-01-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_foldermanager"),
    ]

    operations = [
        migrations.CreateModel(
            name="McqQuestionBase",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="question_images/"
                    ),
                ),
                ("category", models.CharField(max_length=255)),
                ("question_type", models.CharField(max_length=50)),
                ("options", models.JSONField()),
                ("correct_answer", models.CharField(max_length=255)),
                ("instructions", models.TextField()),
                ("last_updated_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
