# Generated by Django 4.1.9 on 2024-01-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_mcqquestionbase"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqquestionbase",
            name="path",
            field=models.CharField(default="root", max_length=400),
            preserve_default=False,
        ),
    ]
