# Generated by Django 4.1.9 on 2024-01-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_mcqquestionbase_copy_qust_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqquestionbase",
            name="Para_quest",
            field=models.TextField(blank=True, null=True),
        ),
    ]
