# Generated by Django 4.1.9 on 2024-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_mcqquestionbase_para_quest"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqquestionbase",
            name="quest_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
