# Generated by Django 4.1.9 on 2024-01-12 04:25

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_mcqquestionbase_quest_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageEditor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
    ]
