# Generated by Django 4.1.9 on 2024-01-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_imageeditor"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcqquestionbase",
            name="explain",
            field=models.TextField(blank=True, null=True),
        ),
    ]
