# Generated by Django 4.1.9 on 2024-01-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_mcqquestionbase_explain"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldermanager",
            name="description",
            field=models.TextField(
                blank=True,
                default="No description is provided for this course",
                null=True,
            ),
        ),
    ]
