# Generated by Django 4.1.9 on 2024-01-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0015_foldermanager_cost_usersubscription_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldermanager",
            name="FolderImage",
            field=models.ImageField(
                default="Folder_profile_img/default.jpg",
                upload_to="Folder_profile_img/",
            ),
        ),
    ]
