# Generated by Django 4.1.9 on 2024-01-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0016_foldermanager_folderimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foldermanager",
            name="FolderImage",
            field=models.ImageField(upload_to="Folder_profile_img/"),
        ),
    ]
