# Generated by Django 4.1.9 on 2024-01-20 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0018_alter_foldermanager_folderimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time_mis", models.CharField(max_length=255)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "q_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
