# Generated by Django 4.1.9 on 2024-01-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="config",
            name="q_path",
            field=models.CharField(max_length=255),
        ),
    ]
