# Generated by Django 4.1.9 on 2024-01-21 03:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_alter_config_q_path"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usersubscription",
            old_name="is_premium",
            new_name="course_premium",
        ),
    ]
