# Generated by Django 4.1.9 on 2024-01-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0022_foldermanager_validity_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="foldermanager",
            name="last_updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
