# Generated by Django 4.1.9 on 2024-01-27 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0023_foldermanager_last_updated_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="validity_days",
            field=models.IntegerField(default=30),
        ),
    ]
