# Generated by Django 4.1.9 on 2024-01-31 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0026_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foldermanager",
            name="FolderName",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
