# Generated by Django 4.1.9 on 2024-01-31 01:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0027_alter_foldermanager_foldername"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderBoard",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("path", models.CharField(max_length=50)),
                ("mark", models.IntegerField()),
                ("attempt", models.IntegerField()),
                ("last_updated_date", models.DateTimeField(auto_now=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
