# Generated by Django 4.1.9 on 2024-01-31 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0028_leaderboard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaderboard",
            name="attempt",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="leaderboard",
            name="mark",
            field=models.IntegerField(default=0),
        ),
    ]
