# Generated by Django 4.1.9 on 2024-02-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0029_alter_leaderboard_attempt_alter_leaderboard_mark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersubscription",
            name="validity_days",
        ),
        migrations.AddField(
            model_name="usersubscription",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
