# Generated by Django 4.1.9 on 2024-02-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0031_paymentdb_alter_usersubscription_updated_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="LatestUpdate",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
