# Generated by Django 4.1.9 on 2024-02-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0032_latestupdate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
